"""
This type stub file was generated by pyright.
"""

from typing import Optional

import gymnasium as gym
import numpy as np
from sb3_contrib import MaskablePPO

from hearthstone.engine.game import Game

MAX_ATK: float
MAX_HP: float
MAX_GOLD: float
MAX_TIER: float
MAX_COST: float
MAX_SPELL_DISCOUNT: float
MAX_CARDS_IN_GAME: int

class HearthstoneEnv(gym.Env[np.ndarray, int]):
    """
    RL Environment for Hearthstone Battlegrounds.

    Action Space (Discrete 32):
    0: End Turn
    1: Roll
    2-8: Buy (Slot 0-6) / DISCOVER_CHOICE (Option 0-2) / TARGET BOARD (Slot 0-6)
    9-15: Sell (Slot 0-6) / TARGET STORE (Slot 0-6)
    [Not implemented in engine yet, usually spells target board]
    16-25: Play Hand (Card 0-9)
    26-31: Swap Right (Slot i <-> Slot i+1)
    26: 0<->1, 27: 1<->2 ... 31: 5<->6
    """

    game: Game
    my_player_id: int
    enemy_id: int
    max_steps_per_episode: int
    steps_taken: int
    actions_in_turn: int
    max_actions_in_turn: int
    opponent_model: Optional[MaskablePPO]
    entity_features: int
    is_targeting: bool
    pending_spell_hand_index: Optional[int]
    pending_target_kind: Optional[str]

    def __init__(self) -> None: ...
    def reset(
        self,
        *,
        seed: int | None = ...,
        options: dict[str, object] | None = ...,
    ) -> tuple[np.ndarray, dict[str, object]]: ...
    def set_opponent(self, model: MaskablePPO) -> None: ...
    def step(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict[str, object]]: ...
    def action_masks(self, player_idx: int | None = ...) -> np.ndarray:
        """
        Return boolean masks valid actions
        True - action is available, False - banned
        Index order = action_space(Discrete 32)
        """
        ...
