"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, List

from .entities import Unit

AuraEffectFn = Callable[[Unit, List[Unit], int], None]
AURA_REGISTRY: Dict[str, AuraEffectFn] = ...

def recalculate_board_auras(board: List[Unit]) -> None: ...
