"""
This type stub file was generated by pyright.
"""

from typing import List
from .entities import Player, Unit
from .enums import BattleOutcome
from .event_system import EventManager

class CombatManager:
    def __init__(self, event_manager: EventManager | None = ...) -> None:
        ...
    
    def get_uid(self) -> int:
        ...
    
    def resolve_combat(self, player_1: Player, player_2: Player) -> tuple[BattleOutcome, int]:
        ...
    
    def check_end_of_battle(self, board_1: List[Unit], board_2: List[Unit], player_1: Player, player_2: Player, combat_players: dict[int, Player]) -> tuple[BattleOutcome, int]:
        ...
    
    def perform_attack(self, attacker: Unit, target: Unit, combat_players: dict[int, Player]) -> None:
        """
        Perform attack with all additional mechanics
        """
        ...
    
    def cleanup_dead(self, boards: List[List[Unit]], attack_indices: List[int], combat_players: dict[int, Player]) -> None:
        """
        Clean board after death and move attack indexes where they should be
        """
        ...
    


