"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Tuple

from .enums import MechanicType

TIER_COPIES: Dict[int, int]
TAVERN_SLOTS: Dict[int, int]
TIER_UPGRADE_COSTS: Dict[int, int]
MECHANIC_DEFAULTS: Dict[MechanicType, Tuple[int, int]]
COST_BUY: int
COST_REROLL: int
SPELLS_PER_ROLL: int
CARD_DB: Dict[str, Any]
SPELL_DB: Dict[str, Any]
