"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, List

from .event_system import EffectContext, Event, TriggerDef

def make_avenge_trigger(
    n: int, effect_fn: Callable[[EffectContext, Event, int], None], name: str = ...
) -> TriggerDef:
    """
    Make TriggerDef for Avenge mechanic (X).
    n: How many allies should die
    effect_fn: function that should play
    """
    ...

TRIGGER_REGISTRY: Dict[str, List[TriggerDef]] = ...
GOLDEN_TRIGGER_REGISTRY: Dict[str, List[TriggerDef]] = ...
SYSTEM_TRIGGER_REGISTRY = ...
