"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Tuple

from .entities import Player
from .event_system import EventManager

class Game:
    players: List[Player]
    turn_count: int
    game_over: bool
    winner_id: Optional[int]
    players_ready: Dict[int, bool]
    event_manager: EventManager

    def __init__(self) -> None: ...
    def step(self, player_idx: int, action_type: str, **kwargs: Any) -> Tuple[bool, bool, str]:
        """
        Make agent move
        Return: [Success, Done, Info]
        """
        ...
