"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional

class CardPool:
    tiers: Dict[int, List[str]]

    def __init__(self) -> None: ...
    def draw_cards(self, count: int, max_tier: int) -> List[str]:
        """
        Достает N карт. Вероятность зависит от кол-ва карт в тирах.
        """
        ...

    def return_cards(self, card_ids: List[str]) -> None:
        """Возвращает карты обратно в пул (при продаже или реролле)"""
        ...

    def draw_discovery_cards(
        self,
        count: int,
        tier: int,
        exact_tier: bool = ...,
        predicate: Optional[Callable[[Dict[str, Any]], bool]] = ...,
    ) -> List[str]:
        """
        Выбирает count УНИКАЛЬНЫХ карт для раскопки и временно изымает их из пула.
        """
        ...

class SpellPool:
    tiers: Dict[int, List[str]]

    def __init__(self) -> None: ...
    def draw_spells(self, count: int, max_tier: int) -> List[str]: ...
