"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Set

from .enums import SpellIDs
from .event_system import TriggerDef

SPELL_TRIGGER_REGISTRY: Dict[str, List[TriggerDef]]
SPELLS_REQUIRE_TARGET: Set[SpellIDs]
