"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Optional, Tuple
from .entities import Player
from .event_system import EventManager
from .pool import CardPool, SpellPool

class TavernManager:
    def __init__(self, pool: CardPool, spell_pool: SpellPool, event_manager: EventManager | None = ...) -> None:
        ...
    
    def get_next_uid(self) -> int:
        ...
    
    def start_turn(self, player: Player, turn_number: int) -> None:
        """
        Logic StartOfTurn
        1. Restore/up gold count
        2. Lower up tavern cost
        3. Restore shop (with freezing)
        """
        ...
    
    def roll_tavern(self, player: Player) -> tuple[bool, str]:
        """Paid roll (1 gold). Ignore freeze (throw all)."""
        ...
    
    def upgrade_tavern(self, player: Player) -> Tuple[bool, str]:
        """Up tavern level"""
        ...
    
    def toggle_freeze(self, player: Player) -> Tuple[bool, str]:
        """Freeze/Unfreeze shop"""
        ...
    
    def buy_unit(self, player: Player, store_index: int) -> Tuple[bool, str]:
        ...
    
    def sell_unit(self, player: Player, board_index: int) -> Tuple[bool, str]:
        ...
    
    def play_unit(self, player: Player, hand_index: int, insert_index: int = ..., target_index: int = ...) -> Tuple[bool, str]:
        """
        Play card hand -> board in concrete position
        Args:
            hand_index: Card index in hand
            insert_index: Index on board, where you should place unit (0 - left, len(board) - right)
            target_index: Index target for battlecry or spell
        """
        ...
    
    def start_discovery(self, player: Player, source: str, tier: Optional[int] = ..., exact_tier: bool = ..., count: int = ..., predicate: Optional[Callable[[Dict[str, Any]], bool]] = ...) -> bool:
        ...
    
    def make_discovery_choice(self, player: Player, index: int) -> Tuple[bool, str]:
        ...
    
    def swap_units(self, player: Player, index_a: int, index_b: int) -> Tuple[bool, str]:
        """
        Swap two units on board
        """
        ...
    
    def end_turn(self, player: Player) -> None:
        ...
    


